version: '3'
services:
  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - scrumpy-backend
  backend:
    build: .
    env_file:
    - .env
    ports:
    - 8080:5000
    networks:
    - scrumpy-backend
  frontend:
    build: .
    env_file:
    - .env
    ports:
    - 80:5000
    networks:
    - scrumpy-frontend

networks:
  scrumpy-backend: